### ISSUE TITLE
why not sign function for gradient under linf norm

### ISSUE THREAD

**Issue by Equationliu** [pralab/Fast-Minimum-Norm-FMN-Attack#3]
Using l2 normalization under linf attack is unreasonable,  which will make the step size much smaller than alpha.

https://github.com/maurapintor/Fast-Minimum-Norm-FMN-Attack/blob/a4aa11cbb2e793e337b2e1c455b45f8ce5e6cccf/src/attacks/fmn.py#L226

**Comment by maurapintor** [comment]
Hi @Equationliu ,
thank you for trying our attack and for suggesting improvements. 
The reason behind chosing L2 normalization instead of a sign operator can be found in the Algorithm 1, line 18, in the paper. Our purpose here is to find the direction vector where the loss decreases, and that direction vector is defined as having Euclidean norm equal to 1. By normalizing in the L-infinity norm, we are indeed changing that direction and forcing the attack to move only in the corners of the L-inf ball, hence there is a risk of overshooting the optimum.

The easiest fix, since the step update is defined as `alpha * gradients`, would be to use a bigger alpha. This was taken into account in the experiments, and you can find it in the section that describes the selection of hyperparameters for all the attacks.

[Fast Minimum-norm Adversarial Attacks through Adaptive Norm Constraints](https://arxiv.org/abs/2102.12827)

**Comment by Equationliu** [comment]
Thanks for your kind reply~
